export const INDIAN_STATES = [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal"
];

export const INDUSTRY_OPTIONS = [
    "Aerospace",
    "Agriculture",
    "Artificial Intelligence",
    "Architecture",
    "Automotive",
    "Banking",
    "Beauty & Personal Care",
    "Biotechnology",
    "Blockchain",
    "Chemical Industry",
    "Construction",
    "Consulting",
    "Consumer Electronics",
    "Cybersecurity",
    "Defense",
    "Education",
    "EdTech",
    "Energy",
    "Event Management",
    "E-commerce",
    "Fashion & Apparel",
    "Finance",
    "FinTech",
    "Fitness & Wellness",
    "FMCG (Fast-Moving Consumer Goods)",
    "Food & Beverage",
    "Furniture",
    "Gaming",
    "Healthcare",
    "HealthTech",
    "Home Decor",
    "Hospitality",
    "Human Resources",
    "Information Technology",
    "Insurance",
    "Interior Design",
    "Investment Management",
    "Legal Services",
    "Logistics",
    "Manufacturing",
    "Marine Industry",
    "Marketing & Advertising",
    "Media & Entertainment",
    "Mining",
    "Oil & Gas",
    "Pharmaceuticals",
    "Printing & Packaging",
    "Real Estate",
    "Renewable Energy",
    "Research & Development",
    "Retail",
    "SaaS (Software as a Service)",
    "Software Development",
    "Sports",
    "Staffing & Recruitment",
    "Telecommunications",
    "Textile",
    "Tourism",
    "Transportation",
    "Waste Management",
    "Others"
];
